version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    cpu_shares: 100
    mem_limit: 754288000
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx650m"
  web:
    image: yakovburtsev/foodtrucks-web
    cpu_shares: 100
    mem_limit: 262144000
    ports:
      - "80:5000"
    links:
      - es